configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/initial_setup.smk"
include: "rules/map_reads.smk"
include: "rules/process_bams.smk"

include: "rules/delly.smk"
include: "rules/dysgu.smk"
include: "rules/nanomonsv.smk"
include: "rules/sniffles.smk"
include: "rules/jasmine.smk"

include: "rules/cutesv.smk"
include: "rules/gatk.smk"
include: "rules/lorax.smk"
include: "rules/pbsv.smk"
include: "rules/svaba.smk"

rule all:
  input:
    expand(f"results/BAMS/{ref}/{{sample}}/{ref}.{{sample}}.sorted.bam.bai", sample=samples),
    expand(f"results/delly/{ref}/{{sample}}/{ref}.{{sample}}.sv.vcf", sample=samples),
    expand(f"results/dysgu/{ref}/{{sample}}/{ref}.{{sample}}.converted.sv.vcf", sample=samples),
    #expand(f"results/nanomonsv/{ref}/{{sample}}/{ref}.{{sample}}.nanomonsv.result.vcf", sample=samples),
    expand(f"results/sniffles/{ref}/{{sample}}/{ref}.{{sample}}.sv.vcf", sample=samples),
    expand(f"results/jasmine/{ref}/{{sample}}/{ref}.{{sample}}.jasmine.merged.sv.vcf", sample=samples),
    #expand(f"results/delly/{ref}/{{sample}}/{ref}.{{sample}}.geno.vcf", sample=samples),
    #expand(f"results/dysgu/{ref}/{{sample}}/{ref}.{{sample}}.geno.vcf", sample=samples),
    #expand(f"results/sniffles/{ref}.{{sample}}/{ref}.{{sample}}.geno.vcf", sample=samples),

    #f"results/jasmine/{ref}/{ref}.ALL.somatic.jasmine.merged.sv.vcf",
