normal: "NHA_p1"
tumors: ["NHA_E6E7_3_p25", "NHA_E6E7_3_p40"]

ref:
  "CHM13v2": /scratch/mkyriakidou/ref/CHM13v2/chm13v2.0.fasta

#dorado 0.3.0
ubams:
  "NHA_p1": /labs/barthel/fastq_DoNotTouch/20230424_0924_3F_PAK78455_fb2f0c71/dorado_0.3.0/NHA_Primary_p1_BR_Whole_C1_OGL14_L66007_PAK78455_NoIndex_L001_fb2f0c71.duplex.ubam
  "NHA_E6E7_3_p25": /labs/barthel/fastq_DoNotTouch/20230424_0924_1F_PAK72403_ce355ea4/dorado_0.3.0/NHA_E6E73_p25_BR_Whole_C1_OGL14_L66005_PAK72403_NoIndex_L001_ce355ea4.duplex.ubam
  "NHA_E6E7_3_p40": /labs/barthel/fastq_DoNotTouch/20230424_0924_3D_PAK72474_3914c8b9/dorado_0.3.0/NHA_E6E73_p40_BR_Whole_C1_OGL14_L66006_PAK72474_NoIndex_L001_3914c8b9.duplex.ubam

repeats: /scratch/rranallo-benavidez/refs/human_chm13v2.0_maskedY_rCRS.trf.bed

chroms: ["chr1", "chr2", "chr3", "chr4", "chr5", "chr6", "chr7", "chr8", "chr9", "chr10", "chr11", "chr12", "chr13", "chr14", "chr15", "chr16", "chr17", "chr18", "chr19", "chr20", "chr21", "chr22", "chrX", "chrY"]
