samples: ["NHA_E6E7_3_p25", "NHA_E6E7_3_p40", "NHA_p1"]
#samples: ["NHA_p1", "NHA_E6E7_3_p25"]
normal: "NHA_p1"

refs:
  "CHM13v2": 
    genome: /scratch/mkyriakidou/ref/CHM13v2/chm13v2.0.fasta

fastqs:
  "NHA_p1":
    ont:
      1: /labs/barthel/fastq_DoNotTouch/20230424_0924_3F_PAK78455_fb2f0c71/guppy_6.4.6+ae70e8f/fastq_pass/NHA_Primary_p1_BR_Whole_C1_OGL14_L66007_PAK78455_NoIndex_L001_Pass.fastq.gz
  "NHA_E6E7_3_p25": 
    ont: 
      1: /labs/barthel/fastq_DoNotTouch/20230424_0924_1F_PAK72403_ce355ea4/guppy_6.4.6+ae70e8f/fastq_pass/NHA_E6E73_p25_BR_Whole_C1_OGL14_L66005_PAK72403_NoIndex_L001_Pass.fastq.gz
  "NHA_E6E7_3_p40": 
    ont: 
      1: /labs/barthel/fastq_DoNotTouch/20230424_0924_3D_PAK72474_3914c8b9/guppy_6.4.6+ae70e8f/fastq_pass/NHA_E6E73_p40_BR_Whole_C1_OGL14_L66006_PAK72474_NoIndex_L001_Pass.fastq.gz

bams:
  "NHA_E6E7_3_p25": /scratch/mkyriakidou/NHA/nha_analysis/BQSR/NHA_E6E7_3_p25/NHA_E6E7_3_p25_BQSR.bam
  "NHA_E6E7_3_p40": /scratch/mkyriakidou/NHA/nha_analysis/BQSR/NHA_E6E7_3_p40/NHA_E6E7_3_p40_BQSR.bam
  "NHA_p1":  /scratch/mkyriakidou/NHA/nha_analysis/BQSR/nha_p1/

repeats: /scratch/rranallo-benavidez/refs/human_chm13v2.0_maskedY_rCRS.trf.bed

chroms: ["chr1", "chr2", "chr3", "chr4", "chr5", "chr6", "chr7", "chr8", "chr9", "chr10", "chr11", "chr12", "chr13", "chr14", "chr15", "chr16", "chr17", "chr18", "chr19", "chr20", "chr21", "chr22", "chrX", "chrY"]
